### ISSUE TITLE
Having trouble getting indices out of obj

### ISSUE THREAD

**Issue by emberlightstudios** [AmionSky/bevy_obj#19]
I'm loading this file here:

https://github.com/makehumancommunity/mpfb2/blob/master/src/mpfb/data/3dobjs/base.obj

and I can see the mesh, but when I try to retrieve the indices arrays I get None.   The primitive topology is set to TriangleList.

I'm trying to modify the mesh in code, so I would need the index arrays. 

If I copy the position, normal, and UV arrays to generate a new mesh, it is not visible.

Not sure what the issue is.  Maybe a bevy bug.

I have also tried loading up the mesh in blender and re-exporing it as an obj.  In that case I was able to get the indices, but not the UVs, even though I verified they were also in the exported file.

**Comment by emberlightstudios** [comment]
EDIT::  I made a mistake.  I was actually loading an obj of the same base mesh I exported from blender.  It wasn't this exact file.  When I try to load this exact file I can't get the indices() array.

**Comment by AmionSky** [comment]
It's because the mesh does not have normals. So it will compute flat normals which requires that no indicies are set, so before it the indicies are removed with `mesh.duplicate_vertices()`.

https://github.com/AmionSky/bevy_obj/blob/b651ceb81a55ecc28c04162b76f9808d1d56601e/src/loader/scene.rs#L137-L142

**Comment by emberlightstudios** [comment]
But how does it render if there is no triangle data?

**Comment by AmionSky** [comment]
There is "triangle data". If there are no indices it just uses the vertices as triangles.

It defaults to flat normals because if you care about normals you should have it precomputed and not use a basic algorithm to compute it at runtime. Flat normals also makes it easier to spot if the mesh was erroneously exported without normals.
And if you don't care about normals then you most likely expecting the model to render with flat normals anyway.

It would be nice if it could be configured plugin wide whether to use flat or smooth normals.

**Comment by emberlightstudios** [comment]
Well I'm not sure how makehuman/mpfb2 handles normals in blender.  Maybe there is some computation in there or maybe it just relies on blender's basic algorithm.  I tried to export the mesh from blender with the normals, but then I wasn't getting any UVs, even though the file clearly had many "vt" lines in it.

Unfortunately all the .target files which contain the many shapekeys of makehuman only have position deltas, no data on normals.  So I don't know any other way to get smooth normals for them other than relying on bevy's compute_smooth_normals function.

**Comment by emberlightstudios** [comment]
But you bring up a good point.  The normals in blender do look much better than the ones generated in bevy when the camera is close.  I don't think I can replicate what they have done.  It is too complex.  Maybe I should abandon this idea and just export all characters from blender instead.  I'll have to rethink this whole character creator idea.

**Comment by AmionSky** [comment]
I would recommend figuring out how to reexport them with normals from blender.

I also created a branch with a way to specify to use smooth normals:
https://github.com/AmionSky/bevy_obj/tree/smooth

**Comment by emberlightstudios** [comment]
Problem is there's too many of them.  I was relying on mesh baking in bevy by reading directly from the files.  There's like 1000 shapekeys or something

**Comment by emberlightstudios** [comment]
I'm looking through the bevy and blender source code to see how they generate smooth normals and as suspected it is a simple average in bevy whereas blender has a more sophisticated algorithm.  However there is a TODO remark in the bevy code that different vector weighting algorithms should be implemented, so I'm hoping that the results will be improved in the future.  And I think I could implement a better technique myself if need be.  It's not as too complicated.  I do still think it makes sense to support smooth normal generation for people such as myself who are working on procedural geometry.  It is your repository though.  Feel free to close this issue.

**Comment by emberlightstudios** [comment]
Since I mentioned losing UV arrays, I should mention I think this is no fault of your plugin.  I can get textures on my imported mesh.  For some reason when I try to take the mesh and modify it with shapekeys, I am losing uv arrays.  I don't understand it yet.  But I was able to get UVs before that.

**Comment by AmionSky** [comment]
Latest release allows customizing the mesh normal generation settings. Also the default normal compute changed to use bevy's default which is smooth if there are indices and flat otherwise.
